# Copyright (C) 2012 Johnny Vestergaard <jkv@unixcluster.dk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


class NormalizerBaseTest(object):

    def does_dict_contain_illegal_keys(self, data_dict):
        """
        Checks if normalized data contains id field. (These are supposed to be generated by the persister)
        """
        stack = [data_dict, ]
        while stack:
            current = stack.pop()
            for key, value in current.items():
                if key.endswith('_id'):
                    return True
                if type(value) == dict:
                    stack.append(value)
        return False
